# Generated by Django 3.1 on 2020-09-15 09:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0003_auto_20200915_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='get_title_slug'),
        ),
    ]
