# Generated by Django 3.1 on 2020-09-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0004_auto_20200915_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
