# Generated by Django 3.1 on 2020-09-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0013_auto_20200915_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shop_system.Category'),
        ),
    ]
