# Generated by Django 3.1 on 2020-09-15 12:00

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0015_auto_20200915_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='shop_system.category', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='get_title_slug'),
        ),
    ]
