# Generated by Django 3.1 on 2020-09-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0020_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
    ]
