# Generated by Django 3.1 on 2020-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0021_auto_20200924_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alternative Title'),
        ),
    ]
